##############################  CLIMATES BAXI ACS Y CLIMATIZACION  ##############################



######## ACS Thermostat ########


- alias: "Set Initial ACS HVAC Mode and Temperature"
  mode: single
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: "00:00:10"
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.acs
      data:
        hvac_mode: >-
          {% if is_state('switch.ap017_habilitar_acs', 'on') %}
            heat
          {% else %}
            off
          {% endif %}
    - service: climate.set_temperature
      target:
        entity_id: climate.acs
      data:
        temperature: "{{ states('number.dp070_t_cons_acs') | float }}"

- alias: "Sync ACS HVAC Mode with Switch"
  mode: single
  trigger:
    - platform: state
      entity_id: switch.ap017_habilitar_acs
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.acs
      data:
        hvac_mode: >-
          {% if is_state('switch.ap017_habilitar_acs', 'on') %}
            heat
          {% else %}
            off
          {% endif %}

- alias: "Sync Switch with ACS HVAC Mode"
  mode: single
  trigger:
    - platform: state
      entity_id: climate.acs
      attribute: hvac_action
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ state_attr('climate.acs', 'hvac_action') == 'heating' }}"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.ap017_habilitar_acs
        - conditions:
            - condition: template
              value_template: "{{ state_attr('climate.acs', 'hvac_action') == 'off' }}"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.ap017_habilitar_acs

- alias: "Sync ACS target_temp with dp070_t_cons_acs"
  mode: single
  trigger:
    - platform: state
      entity_id: number.dp070_t_cons_acs
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.acs
      data:
        temperature: "{{ states('number.dp070_t_cons_acs') | float }}"

- alias: "Sync ACS dp070_t_cons_acs with target_temp"
  mode: single
  trigger:
    - platform: state
      entity_id: climate.acs
      attribute: temperature
  condition:
    - condition: template
      value_template: >
        {% set climate_temp = state_attr('climate.acs', 'temperature') | float %}
        {% set number_temp = states('number.dp070_t_cons_acs') | float %}
        {{ climate_temp != number_temp }}
  action:
    - service: number.set_value
      target:
        entity_id: number.dp070_t_cons_acs
      data:
        value: "{{ state_attr('climate.acs', 'temperature') }}"



######## Climatizacion Dual Mode Thermostat ########


- alias: "Set Initial Climatizacion HVAC Mode and Temperature"
  mode: single
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: "00:00:10"
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.climatizacion
      data:
        hvac_mode: >-
          {% if is_state('switch.ap016_habilitar_climatizacion', 'on') %}
            {% if is_state('switch.ap015_habilitar_aacc', 'on') %}
              cool
            {% else %}
              heat
            {% endif %}
          {% else %}
            off
          {% endif %}
    - service: climate.set_temperature
      target:
        entity_id: climate.climatizacion
      data:
        temperature: "{{ states('number.cp200_t_cons_manual') | float }}"

- alias: "Sync Climatizacion HVAC Mode with Switches"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - switch.ap015_habilitar_aacc
        - switch.ap016_habilitar_climatizacion
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.climatizacion
      data:
        hvac_mode: >-
          {% if is_state('switch.ap016_habilitar_climatizacion', 'on') %}
            {% if is_state('switch.ap015_habilitar_aacc', 'on') %}
              cool
            {% else %}
              heat
            {% endif %}
          {% else %}
            off
          {% endif %}

- alias: "Sync Switches with Climatizacion HVAC Mode"
  mode: single
  trigger:
    - platform: state
      entity_id: climate.climatizacion
      attribute: hvac_action
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ state_attr('climate.climatizacion', 'hvac_action') == 'heating' }}"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.ap016_habilitar_climatizacion
            - service: switch.turn_off
              target:
                entity_id: switch.ap015_habilitar_aacc
            - service: climate.set_temperature
              target:
                entity_id: climate.climatizacion
              data:
                temperature: "{{ states('number.cp200_t_cons_manual') | float }}"
        - conditions:
            - condition: template
              value_template: "{{ state_attr('climate.climatizacion', 'hvac_action') == 'cooling' }}"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.ap016_habilitar_climatizacion
            - service: switch.turn_on
              target:
                entity_id: switch.ap015_habilitar_aacc
            - service: climate.set_temperature
              target:
                entity_id: climate.climatizacion
              data:
                temperature: "{{ states('number.cp200_t_cons_manual') | float }}"
        - conditions:
            - condition: template
              value_template: "{{ state_attr('climate.climatizacion', 'hvac_action') == 'off' }}"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.ap016_habilitar_climatizacion
            - service: switch.turn_off
              target:
                entity_id: switch.ap015_habilitar_aacc

- alias: "Sync Climatizacion target_temp with cp200_t_cons_manual"
  mode: single
  trigger:
    - platform: state
      entity_id: number.cp200_t_cons_manual
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.climatizacion
      data:
        temperature: "{{ states('number.cp200_t_cons_manual') | float }}"

- alias: "Sync cp200_t_cons_manual with Climatizacion target_temp"
  mode: single
  trigger:
    - platform: state
      entity_id: climate.climatizacion
      attribute: temperature
  condition:
    - condition: template
      value_template: >
        {% set climate_temp = state_attr('climate.climatizacion', 'temperature') | float %}
        {% set number_temp = states('number.cp200_t_cons_manual') | float %}
        {{ climate_temp != number_temp }}
  action:
    - service: number.set_value
      target:
        entity_id: number.cp200_t_cons_manual
      data:
        value: "{{ state_attr('climate.climatizacion', 'temperature') }}"



##############################  END  ##############################